const workPortfolio = [
    {
        id: 0,
        type: "react",
        name: "Movies",
        img: "./imgs/react_movies.jpg",
        img_large: ["./imgs/large/movies-large.jpg", "./imgs/large/movie-mobile-large1.jpg"],
        link: "https://belen-dominguez.github.io/React_TP-Movies/#/",
        status: "Completed",
        description:"Final ADA ITW project. Search and checkout latest movies and series. Implemented: API, axios, react router and others.",
        date: "5/20/2020"
    },
    {
        id: 1,
        type: "react",
        name: "Music Player",
        img: "./imgs/react-musicPLayer.jpg",
        img_large: ["./imgs/large/music-player-large.jpg", "./imgs/large/music-player-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/React-MusicPlayer/",
        status: "Completed",
        description: "Practicing with React JS. Developing a music player with a library of music.",
        date: '2/8/2021'
    },
    {
        id: 2,
        type: "react",
        name: "Portfolio",
        img: "./imgs/react-portfolio.jpg",
        img_large: "./imgs/large/portfolio-large.jpg",
        link: "https://belen-dominguez.github.io/react-portfolio-app/#/",
        status: "Completed",
        description: "Practicing with React JS, developing a portfolio. Implemented: react router, animations with framer motion, styled components, etc. ",
        date: '2/9/2021'
    },
    {
        id: 3,
        type: "react",
        name: "Todo List",
        img: "./imgs/react_todoList.jpg",
        img_large: "./imgs/large/todo-large.jpg",
        link: "https://belen-dominguez.github.io/React_TP-todoList/",
        status: "Completed",
        description: "First ADA ITW react project. A todo list.",
        date: "5/20/2020"
    },
    {
        id: 4,
        type: "javascript",
        name: "Memotest",
        img: "./imgs/memotest-preview.jpg",
        img_large: "./imgs/large/memotest-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/30-memotest/",
        status: "Completed",
        description:" Practicing with Javascript. Developing a memotest game. In local storage best score is saved. You can access the history of your current games and total amount of points.",
        date: '2/9/2021'
    },
    {
        id: 5,
        type: "javascript",
        name: "Weather App",
        img: "./imgs/weather-preview.png",
        img_large: "./imgs/large/weather-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/28-weather-app/",
        status: "Completed",
        description: "Practicing with Javascript. Developing a weather app witch also displays information of countries. Fun Project!!",
        date: '2/9/2021'
    },
    {
        id: 6,
        type: "javascript",
        name: "Multi Step Form",
        img: "./imgs/multistep-preview.jpg",
        img_large: "./imgs/large/multi-form-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/25-multi-step-form/",
        status: "Completed",
        description: "Developing a multi step form for a service company",
        date: "5/20/2020"
    },
    {
        id: 7,
        type: "javascript",
        name: "Sign Up Landing",
        img: "./imgs/signUp-preview.jpg",
        img_large: "./imgs/large/sign-up-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/29-sign-up-page/",
        status: "Completed",
        description: "Trying different things with the password input.",
        date: "5/20/2020"
    },
    {
        id: 8,
        type: "javascript",
        name: "Job Listing",
        img: "./imgs/jobListing-preview.jpg",
        img_large: "./imgs/large/jobListin-api-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/26-job-listing/",
        status: "Completed",
        description: "Practicing with Javascript & Api's, getting job positions from diferent countries. Implementing filters.",
        date: "1/20/2021"
    },
    {
        id: 9,
        type: "javascript",
        name: "Book Store",
        img: "./imgs/bookstore-preview.jpg",
        img_large: ["./imgs/large/book-store-large1.jpg", "./imgs/large/book-store-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/27-book-store-app/",
        status: "Completed",
        description:"Practicing with Javascript & Api's, getting book's information based on categories and names. Implemented search input and Favorites section!",
        date: "1/20/2021"
    },
    {
        id: 10,
        type: "javascript",
        name: "Slideshow",
        img: "./imgs/slideshow-preview.jpg",
        img_large: "./imgs/large/slideshow-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/24-slideshow/",
        status: "Completed",
        description: "Own javascript development for tabs and slideshows, adjusting images width's. Fun project!!",
        date: "1/20/2021"
    },
    {
        id: 11,
        type: "javascript",
        name: "Breaking Bad API",
        img: "./imgs/breakingBad-preview.jpg",
        img_large: "./imgs/large/breaking-bad-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/19-BreakingBad_API/",
        status: "Completed",
        description:"Javascript ADA-ITW project. Displaying characters, details & quotes with Api's",
        date: "5/20/2020"
    },
    {
        id: 12,
        type: "javascript",
        name: "Kittens API",
        img: "./imgs/gatitos-preview.jpg",
        img_large: ["./imgs/large/buscador-gatitos-large1.jpg", "./imgs/large/buscador-gatitos-large2.jpg","./imgs/large/buscador-gatitos-large3.jpg"],
        link: "https://belen-dominguez.github.io/ada_itw/21-Busqueda_gatitos/",
        status: "Completed",
        description:"Javascript ADA-ITW project. Implementing api's, search & filter kitten breed, beautiful kitten images <3. Great project! ",
        date: "5/20/2020"
    },
    {
        id: 13,
        type: "javascript",
        name: "Array 2D Lists",
        img: "./imgs/sublistas_preview.jpg",
        img_large: "./imgs/large/array2d-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/16-sublistas/",
        status: "Completed",
        description:"Playing with Javascript and 2D arrays. Fun!!",
        date: "5/20/2020"
    },
    {
        id: 14,
        type: "javascript",
        name: "Sales App",
        img: "./imgs/VentaPc-preview.jpg",
        img_large: ["./imgs/large/sales-large1.jpg", "./imgs/large/sales-large2.jpg"],
        link: "https://belen-dominguez.github.io/ada_itw/18-Ventas-PC/",
        status: "Completed",
        description:"Javascript ADA-ITW project. Creating a sales administration app.",
        date: "5/20/2020"
    },
    {
        id: 15,
        type: "javascript",
        name: "Calculator App",
        img: "./imgs/calc_preview.jpg",
        img_large: "./imgs/large/calc-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/14-Calculadora/",
        status: "Completed",
        description: "Javascript ADA-ITW project. Creating my own calculator.",
        date: "5/20/2020"
    },
    {
        id: 16,
        type: "html",
        name: "Mix Landing",
        img: "./imgs/mix-preview.jpg",
        img_large: "./imgs/large/mix-landing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/19-Mix-landing/",
        status: "Completed",
        description:"Practising HTML  & CSS, creating a landing page.",
        date: "5/20/2020"
    },
    {
        id: 17,
        type: "html",
        name: "Key Login",
        img: "./imgs/key-preview.jpg",
        img_large: "./imgs/large/key-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/22-Key-login/",
        status: "Completed",
        description:"Practising HTML & CSS hacks with checkbox inputs.",
        date: "5/20/2020"
    },
    {
        id: 18,
        type: "html",
        name: "Pricing Table",
        img: "./imgs/pricing-preview.jpg",
        img_large: ["./imgs/large/pricing-large.jpg", "./imgs/large/pricing-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/15-Pricing/",
        status: "Completed",
        description:"Practising HTML & CSS, mobile responsive.",
        date: "5/20/2020"
    },
    {
        id: 19,
        type: "html",
        name: "Trendz Login",
        img: "./imgs/trendz-design.jpg",
        img_large: "./imgs/large/trendz-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/21-Trendz-login/",
        status: "Completed",
        description:"Practising HTML & CSS, developing a login page.",
        date: "5/20/2020"
    },
    {
        id: 20,
        type: "html",
        name: "Job Listing",
        img: "./imgs/job-listing-preview.jpg",
        img_large: "./imgs/large/job-listing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/14-Job-listings/",
        status: "Completed",
        description:"Practising HTML & CSS, mobile responsive.",
        date: "5/20/2020"
    },
    {
        id: 21,
        type: "html",
        name: "Faq Landing",
        img: "./imgs/faq-preview.jpg",
        img_large: "./imgs/large/faq-landing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/23-FAQ-page/",
        status: "Completed",
        description:"Practising HTML & CSS hacks with checkbox inputs.",
        date: "5/20/2020"
    },
    {
        id: 22,
        type: "html",
        name: "Fylo Dark Landing",
        img: "./imgs/fylodark-preview.jpg",
        img_large: ["./imgs/large/fylo-dark-large.jpg","./imgs/large/fylo-dark-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/10-Fylodark_landing/",
        status: "Completed",
        description:"Practising HTML & CSS, mobile responsive, creating landing pages. Some of my first works.",
        date: "5/20/2020"
    },
    {
        id: 23,
        type: "html",
        name: "Bookmark Landing",
        img: "./imgs/bookmark-preview.jpg",
        img_large: ["./imgs/large/bookmark-large.jpg", "./imgs/large/bookmark-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/16-Bookmark-landing/",
        status: "Completed",
        description:"Practising HTML & CSS, mobile responsive, creating landing pages. Some of my first works.",
        date: "5/20/2020"
    },
    {
        id: 24,
        type: "html",
        name: "Social Media Dashboard",
        img: "./imgs/social-preview.jpg",
        img_large: ["./imgs/large/social-dash-large1.jpg", "./imgs/large/social-dash-large2.jpg", "./imgs/large/social-dash-mobile-large1.jpg"],
        link: "https://belen-dominguez.github.io/practicas/06-social-media/index.html",
        status: "Completed",
        description:"Creating landing pages. Practising HTML & CSS. Switching template styles. Mobile responsive. Some of my first works.",
        date: "5/20/2020"
    },
    {
        id: 25,
        type: "html",
        name: "Four Card Landing",
        img: "./imgs/fourCard-preview.jpg",
        img_large: ["./imgs/large/four-card-large.jpg", "./imgs/large/four-card-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/09-Four-card_landing/",
        status: "Completed",
        description: "A nice layout-based challenge for beginners. This will test anyone who is new to multi-column and responsive layouts.",
        date: "5/20/2020"
    },
    {
        id: 26,
        type: "html",
        name: "Captivate Landing",
        img: "./imgs/captivate-preview.jpg",
        img_large: "./imgs/large/captivate-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/17-Captivate/",
        status: "Complete",
        description:"Creating landing pages. Practising HTML & CSS.  Some of my first works.",
        date: "5/20/2020"
    },
    {
        id: 27,
        type: "html",
        name: "Usance Landing",
        img: "./imgs/usance-preview.jpg",
        img_large: ["./imgs/large/usance-large.jpg", "./imgs/large/usance-mobile-lareg.jpg"],
        link: "https://belen-dominguez.github.io/practicas/18-Usance-landing/",
        status: "Complete",
        description: 'Creating landing pages. Practising HTML & CSS. Mobile responsive. Some of my first works.',
        date: "5/20/2020"
    },
    {
        id: 28,
        type: "javascript",
        name: "Puzzle App",
        img: "./imgs/puzzle-preview.jpg",
        img_large: ["./imgs/large/puzzle-large2.jpg","./imgs/large/puzzle-large1.jpg",  "./imgs/large/puzzle-large3.jpg"],
        link: "https://belen-dominguez.github.io/practicas/31-puzzle-app/",
        status: "Complete",
        description: 'For Desktop. Research and practice of drag and drop API.',
        date: '2/9/2021'
    },
    {
        id: 29,
        type: "javascript",
        name: "Sliding Puzzle App",
        img: "./imgs/slidingPuzzle-preview.jpg",
        img_large: ["./imgs/large/slidingPuzzle-large.jpg","./imgs/large/slidingPuzzle-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/32-sliding-puzzle",
        status: "Complete",
        description: 'For Desktop. Practising JS, Sliding puzzle.',
        date: '2/17/2021'
    },
    {
        id: 30,
        type: "javascript - html - animation",
        name: "Landing with Animations",
        img: "./imgs/landingAnimations-preview.jpg",
        img_large: ["./imgs/large/landingAnimations-large.jpg","./imgs/large/landingAnimations-large2.jpg", "./imgs/large/landingAnimations-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/33-landing-animations",
        status: "Complete",
        description: 'Practising JS and animations. Mobile responsibe.',
        date: '2/17/2021'
    },
    {
        id: 31,
        type: "javascript",
        name: "Trello Clone",
        img: "./imgs/trello-clone-preview.jpg",
        img_large: ["./imgs/large/trello-clone-large1.jpg","./imgs/large/trello-clone-large2.jpg", "./imgs/large/trello-clone-large3.jpg"],
        link: "https://belen-dominguez.github.io/practicas/34-Dnd-app",
        status: "Complete",
        description: 'Practising JS and Drag and Drop API. A trello clone, only for desktop.',
        date: '2/26/2021'
    },
    {
        id: 32,
        type: "javascript - html - animation",
        name: "Card Effect Animation",
        img: "./imgs/cardEffect-preview.jpg",
        img_large: ["./imgs/large/cardEffect-large1.jpg","./imgs/large/cardEffect-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/35-card-animation",
        status: "Complete",
        description: 'Practising JS and CSS animation. Applying card transition effects, menu toggle and background change. No libraries. Only for desktop.',
        date: '3/9/2021'
    },
    {
        id: 33,
        type: "javascript - html - animation",
        name: "Clone Nascostify Landing",
        img: "./imgs/nascostify-preview.jpg",
        img_large: ["./imgs/large/nascostify-large1.jpg","./imgs/large/nascostify-large1.jpg"],
        link: "https://belen-dominguez.github.io/practicas/36-landing_nascostify",
        status: "Complete",
        description: 'Practising JS and CSS animation. Clone of landing: nascostify.com. Applying scroll animations. No libraries. Only for desktop.',
        date: '3/27/2021'
    },
    {
        id: 34,
        type: "javascript - html - animation",
        name: "Clone WannaThis Landing",
        img: "./imgs/wanna-preview.jpg",
        img_large: ["./imgs/large/wanna-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/37-landing_wanna",
        status: "Complete",
        description: 'Practising JS and CSS animation. Clone of landing: wannathis.one. Applying scroll animations. No libraries. Only for desktop.',
        date: '3/31/2021'
    },

]



const workPortfolioEsp = [
    {
        id: 0,
        type: "react",
        name: "Películas",
        img: "./imgs/react_movies.jpg",
        img_large: ["./imgs/large/movies-large.jpg", "./imgs/large/movie-mobile-large1.jpg"],
        link: "https://belen-dominguez.github.io/React_TP-Movies/#/",
        status: "Terminado",
        description:"Trabajo final en ADA ITW. Buscador de películas. Se implementó: API, axios, react router and others.",
        date: "5/20/2020"
    },
    {
        id: 1,
        type: "react",
        name: "Music Player",
        img: "./imgs/react-musicPLayer.jpg",
        img_large: ["./imgs/large/music-player-large.jpg", "./imgs/large/music-player-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/React-MusicPlayer/",
        status: "Terminado",
        description: "Practicando React JS. Desarrollo de un reproductor de música, con su librería de canciones.",
        date: '2/9/2021'
    },
    {
        id: 2,
        type: "react",
        name: "Portfolio",
        img: "./imgs/react-portfolio.jpg",
        img_large: "./imgs/large/portfolio-large.jpg",
        link: "https://belen-dominguez.github.io/react-portfolio-app/#/",
        status: "Terminado",
        description: "Practicando React JS, desarrollo de un portfolio. Se implementó: react router, animaciones con framer motion, styled components, etc. ",
        date: '2/9/2021'
    },
    {
        id: 3,
        type: "react",
        name: "Lista de Tareas",
        img: "./imgs/react_todoList.jpg",
        img_large: "./imgs/large/todo-large.jpg",
        link: "https://belen-dominguez.github.io/React_TP-todoList/",
        status: "Terminado",
        description: "Primer trabajo de React en ADA ITW. Una lista de tareas",
        date: "5/20/2020"
    },
    {
        id: 4,
        type: "javascript",
        name: "Memotest",
        img: "./imgs/memotest-preview.jpg",
        img_large: "./imgs/large/memotest-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/30-memotest/",
        status: "Terminado",
        description:" Practicando Javascript. Desarrollo del juego memotest. En el mismo se guarda de forma local la mejor puntuación. Se puede acceder al historial de juegos en la sesión corriente, como también la suma total de puntos.",
        date: '2/9/2021'
    },
    {
        id: 5,
        type: "javascript",
        name: "Clima App",
        img: "./imgs/weather-preview.png",
        img_large: "./imgs/large/weather-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/28-weather-app/",
        status: "Terminado",
        description: "Practicando Javascript. Desarrollo de aplicación sobre el clima, la cual también muestra información sobre los países. Excelente proyecto!!",
        date: '2/9/2021'
    },
    {
        id: 6,
        type: "javascript",
        name: "Formulario Multi Step",
        img: "./imgs/multistep-preview.jpg",
        img_large: "./imgs/large/multi-form-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/25-multi-step-form/",
        status: "Terminado",
        description: "Desarrollo de un formulario con varios pasos para una emrpesa de servicios.",
        date: "1/20/2021"
    },
    {
        id: 7,
        type: "javascript",
        name: "Landing de Registro",
        img: "./imgs/signUp-preview.jpg",
        img_large: "./imgs/large/sign-up-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/29-sign-up-page/",
        status: "Terminado",
        description: "Implementando diferentes funciones en el campo de contraseña.",
        date: "5/20/2020"
    },
    {
        id: 8,
        type: "javascript",
        name: "Listado de trabajos",
        img: "./imgs/jobListing-preview.jpg",
        img_large: "./imgs/large/jobListin-api-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/26-job-listing/",
        status: "Terminado",
        description: "Practicando Javascript & Api's, buscando puestos de trabajo en diferentes países. Se implementaron filtros.",
        date: "1/20/2021"
    },
    {
        id: 9,
        type: "javascript",
        name: "Tienda de libros",
        img: "./imgs/bookstore-preview.jpg",
        img_large: ["./imgs/large/book-store-large1.jpg", "./imgs/large/book-store-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/27-book-store-app/",
        status: "Terminado",
        description:"Practicando Javascript & Api's, solitando información de libros, búsquedas por categorías y nombres. Se implementó un buscador y una sección de favoritos!",
        date: "1/20/2021"
    },
    {
        id: 10,
        type: "javascript",
        name: "Slideshow",
        img: "./imgs/slideshow-preview.jpg",
        img_large: "./imgs/large/slideshow-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/24-slideshow/",
        status: "Terminado",
        description: "Desarrollo propio en javascript de un módulo con tabs y slideshow. Por funciones ajustamos en display de la cantidad de imagenes a mostrar. Excelente proyecto!!",
        date: "1/20/2021"
    },
    {
        id: 11,
        type: "javascript",
        name: "Breaking Bad API",
        img: "./imgs/breakingBad-preview.jpg",
        img_large: "./imgs/large/breaking-bad-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/19-BreakingBad_API/",
        status: "Terminado",
        description:"Proyecto en javascript en ADA-ITW. Se muestran los personajes, citas, etc con la Api's",
        date: "5/20/2020"
    },
    {
        id: 12,
        type: "javascript",
        name: "Buscador de Gatitos",
        img: "./imgs/gatitos-preview.jpg",
        img_large: ["./imgs/large/buscador-gatitos-large1.jpg", "./imgs/large/buscador-gatitos-large2.jpg","./imgs/large/buscador-gatitos-large3.jpg"],
        link: "https://belen-dominguez.github.io/ada_itw/21-Busqueda_gatitos/",
        status: "Terminado",
        description:"Proyecto en javascript, ADA-ITW. Implementando api's, buscador y filtros de gatitos. Hermoso proyecto! ",
        date: "5/20/2020"
    },
    {
        id: 13,
        type: "javascript",
        name: "Listas con Array 2D",
        img: "./imgs/sublistas_preview.jpg",
        img_large: "./imgs/large/array2d-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/16-sublistas/",
        status: "Terminado",
        description:"Practicando Javascript y arrays 2D. Divertido!!",
        date: "5/20/2020"
    },
    {
        id: 14,
        type: "javascript",
        name: "App de Ventas",
        img: "./imgs/VentaPc-preview.jpg",
        img_large: ["./imgs/large/sales-large1.jpg", "./imgs/large/sales-large2.jpg"],
        link: "https://belen-dominguez.github.io/ada_itw/18-Ventas-PC/",
        status: "Terminado",
        description:"Proyecto javascript en ADA-ITW. Creando una aplicación de administracón de ventas.",
        date: "5/20/2020"
    },
    {
        id: 15,
        type: "javascript",
        name: "Calculadora",
        img: "./imgs/calc_preview.jpg",
        img_large: "./imgs/large/calc-large.jpg",
        link: "https://belen-dominguez.github.io/ada_itw/14-Calculadora/",
        status: "Terminado",
        description: "Proyecto javascript en ADA-ITW. Desarrollando una calculadora.",
        date: "5/20/2020"
    },
    {
        id: 16,
        type: "html",
        name: "Mix Landing",
        img: "./imgs/mix-preview.jpg",
        img_large: "./imgs/large/mix-landing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/19-Mix-landing/",
        status: "Terminado",
        description:"Practicando HTML  & CSS, creación de landing page.",
        date: "5/20/2020"
    },
    {
        id: 17,
        type: "html",
        name: "Key Login",
        img: "./imgs/key-preview.jpg",
        img_large: "./imgs/large/key-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/22-Key-login/",
        status: "Terminado",
        description:"Practicando HTML & hacks de CSS con checkbox.",
        date: "5/20/2020"
    },
    {
        id: 18,
        type: "html",
        name: "Tabla de Precios",
        img: "./imgs/pricing-preview.jpg",
        img_large: ["./imgs/large/pricing-large.jpg", "./imgs/large/pricing-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/15-Pricing/",
        status: "Terminado",
        description:"Practicando HTML & CSS, mobile responsive.",
        date: "5/20/2020"
    },
    {
        id: 19,
        type: "html",
        name: "Trendz Login",
        img: "./imgs/trendz-design.jpg",
        img_large: "./imgs/large/trendz-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/21-Trendz-login/",
        status: "Terminado",
        description:"Practicando HTML & CSS, creación de landing page.",
        date: "5/20/2020"
    },
    {
        id: 20,
        type: "html",
        name: "Job Listing",
        img: "./imgs/job-listing-preview.jpg",
        img_large: "./imgs/large/job-listing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/14-Job-listings/",
        status: "Terminado",
        description:"Practicando HTML & CSS, mobile responsive.",
        date: "5/20/2020"
    },
    {
        id: 21,
        type: "html",
        name: "Faq Landing",
        img: "./imgs/faq-preview.jpg",
        img_large: "./imgs/large/faq-landing-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/23-FAQ-page/",
        status: "Terminado",
        description:"Practicando HTML & hacks de CSS con checkbox.",
        date: "5/20/2020"
    },
    {
        id: 22,
        type: "html",
        name: "Fylo Dark Landing",
        img: "./imgs/fylodark-preview.jpg",
        img_large: ["./imgs/large/fylo-dark-large.jpg","./imgs/large/fylo-dark-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/10-Fylodark_landing/",
        status: "Terminado",
        description:"Practicando HTML & CSS, mobile responsive, creando landing pages. De mis primeros trabajos.",
        date: "5/20/2020"
    },
    {
        id: 23,
        type: "html",
        name: "Bookmark Landing",
        img: "./imgs/bookmark-preview.jpg",
        img_large: ["./imgs/large/bookmark-large.jpg", "./imgs/large/bookmark-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/16-Bookmark-landing/",
        status: "Terminado",
        description:"Practicando HTML & CSS, mobile responsive, creando landing pages. De mis primeros trabajos.",
        date: "5/20/2020"
    },
    {
        id: 24,
        type: "html",
        name: "Social Media Dashboard",
        img: "./imgs/social-preview.jpg",
        img_large: ["./imgs/large/social-dash-large1.jpg", "./imgs/large/social-dash-large2.jpg", "./imgs/large/social-dash-mobile-large1.jpg"],
        link: "https://belen-dominguez.github.io/practicas/06-social-media/index.html",
        status: "Terminado",
        description:"Creando landing pages. Practicando HTML & CSS. Cambio de estilos. Mobile responsive. De mis primeros trabajos.",
        date: "5/20/2020"
    },
    {
        id: 25,
        type: "html",
        name: "Four Card Landing",
        img: "./imgs/fourCard-preview.jpg",
        img_large: ["./imgs/large/four-card-large.jpg", "./imgs/large/four-card-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/09-Four-card_landing/",
        status: "Terminado",
        description: "Creando landing pages. Practicando HTML & CSS. Jugando con multi-columns. Mobile responsive. De mis primeros trabajos.",
        date: "5/20/2020"
    },
    {
        id: 26,
        type: "html",
        name: "Captivate Landing",
        img: "./imgs/captivate-preview.jpg",
        img_large: "./imgs/large/captivate-large.jpg",
        link: "https://belen-dominguez.github.io/practicas/17-Captivate/",
        status: "Terminado",
        description:"Creando landing pages. Practicando HTML & CSS.  De mis primeros trabajos.",
        date: "5/20/2020"
    },
    {
        id: 27,
        type: "html",
        name: "Usance Landing",
        img: "./imgs/usance-preview.jpg",
        img_large: ["./imgs/large/usance-large.jpg", "./imgs/large/usance-mobile-lareg.jpg"],
        link: "https://belen-dominguez.github.io/practicas/18-Usance-landing/",
        status: "Terminado",
        description: 'Creando landing pages. Practicando HTML & CSS.  De mis primeros trabajos.',
        date: "5/20/2020"
    },
    {
        id: 28,
        type: "javascript",
        name: "Puzzle App",
        img: "./imgs/puzzle-preview.jpg",
        img_large: ["./imgs/large/puzzle-large2.jpg","./imgs/large/puzzle-large1.jpg",  "./imgs/large/puzzle-large3.jpg"],
        link: "https://belen-dominguez.github.io/practicas/31-puzzle-app/",
        status: "Terminado",
        description: 'Para Desktop. Practicando drag and drop.',
        date: '2/9/2021'
    },
    {
        id: 29,
        type: "javascript",
        name: "Sliding Puzzle App",
        img: "./imgs/slidingPuzzle-preview.jpg",
        img_large: ["./imgs/large/slidingPuzzle-large.jpg","./imgs/large/slidingPuzzle-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/32-sliding-puzzle",
        status: "Terminado",
        description: 'Para Desktop. Practicando JS, Rompecabezas deslizante.',
        date: '2/17/2021'
    },
    {
        id: 30,
        type: "javascript - html - animation",
        name: "Landing con Animaciones",
        img: "./imgs/landingAnimations-preview.jpg",
        img_large: ["./imgs/large/landingAnimations-large.jpg","./imgs/large/landingAnimations-large2.jpg", "./imgs/large/landingAnimations-mobile-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/33-landing-animations",
        status: "Terminado",
        description: 'Practicando JS y animaciones. Adaptado a mobile.',
        date: '2/17/2021'
    },
    {
        id: 31,
        type: "javascript",
        name: "Trello Clone",
        img: "./imgs/trello-clone-preview.jpg",
        img_large: ["./imgs/large/trello-clone-large1.jpg","./imgs/large/trello-clone-large2.jpg", "./imgs/large/trello-clone-large3.jpg"],
        link: "https://belen-dominguez.github.io/practicas/34-Dnd-app",
        status: "Terminado",
        description: 'Practicando JS y Drag and Drop API. Clon de Trello, sólo desktop.',
        date: '2/26/2021'
    },
    {
        id: 32,
        type: "javascript - html - animation",
        name: "Card Effect Animation",
        img: "./imgs/cardEffect-preview.jpg",
        img_large: ["./imgs/large/cardEffect-large1.jpg","./imgs/large/cardEffect-large2.jpg"],
        link: "https://belen-dominguez.github.io/practicas/35-card-animation",
        status: "Terminado",
        description: 'Practicando animaciones con JS y CSS. Si aplicó un efecto de transición en las tarjetas, menu toggle y cambios en el background. Sin librerías. Sólo desktop.',
        date: '3/9/2021'
    },
    {
        id: 33,
        type: "javascript - html - animation",
        name: "Clone Nascostify Landing",
        img: "./imgs/nascostify-preview.jpg",
        img_large: ["./imgs/large/nascostify-large1.jpg","./imgs/large/nascostify-large1.jpg"],
        link: "https://belen-dominguez.github.io/practicas/36-landing_nascostify",
        status: "Terminado",
        description: 'Practicando animaciones con JS y CSS. Clone de landing: nascostify.com. Aplicando efectos al scrollear. Sin librerías. Sólo desktop.',
        date: '3/27/2021'
    },
    {
        id: 34,
        type: "javascript - html - animation",
        name: "Clone WannaThis Landing",
        img: "./imgs/wanna-preview.jpg",
        img_large: ["./imgs/large/wanna-large.jpg"],
        link: "https://belen-dominguez.github.io/practicas/37-landing_wanna",
        status: "Terminado",
        description: 'Practicando animaciones con JS y CSS. Clone de landing: wannathis.one. Aplicando efectos al scrollear. Sin librerías. Sólo desktop.',
        date: '3/31/2021'
    },

]